services:
  - type: web
    name: bloodbank-management
    runtime: python
    buildCommand: "./build.sh"
    startCommand: >-
      cd BBM && 
      if [ -f /tmp/db/db.sqlite3 ]; then 
        ln -sf /tmp/db/db.sqlite3 db.sqlite3; 
      fi && 
      PYTHONPATH=/opt/render/project/src python manage.py collectstatic --no-input && 
      PYTHONPATH=/opt/render/project/src python manage.py migrate && 
      PYTHONPATH=/opt/render/project/src gunicorn bloodbankmanagement.wsgi:application
    envVars:
      - key: DATABASE_URL
        value: ''
      - key: SECRET_KEY
        value: '+zy!9k=9pql5gz9bkqjore)k6r!%w0atk(@(!(!zvp5e(t2i8n'
      - key: PYTHON_VERSION
        value: 3.10.6
      - key: WEB_CONCURRENCY
        value: 4
